LF-10909-6: vvcam: isp_gcmono: Fix build issues with upstream kernel next-20231129
This function of isp_gcmono is only defined but not call, and all the warnings
will be treated as errors. So it is just used under the mocro ISP_GCMONO.

vvcam/v4l2/isp/isp_gcmono.c:128:12: error: 'isp_s_gcmonoWriteData' defined but not used [-Werror=unused-function]
vvcam/v4l2/isp/isp_gcmono.c:104:12: error: 'isp_s_gcmonopx' defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>