LF-10909-7: vvcam: isp_ioctl: Fix build issues with upstream kernel next-20231129
The functions of the isp_ioctl are called global. These should be define
in the header file globally.

vvcam/v4l2/isp/isp_ioctl.c:363:5: error: no previous prototype for 'isp_s_digital_gain' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:602:5: error: no previous prototype for 'isp_awb_control' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:790:5: error: no previous prototype for 'isp_cc_control' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:851:5: error: no previous prototype for 'isp_enable_gamma_out_ctrl' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:889:5: error: no previous prototype for 'isp_s_gamma_out_ctrl' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:999:5: error: no previous prototype for 'isp_ioc_read_reg' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1009:5: error: no previous prototype for 'isp_ioc_write_reg' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1018:5: error: no previous prototype for 'isp_ioc_disable_isp_off' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1276:5: error: no previous prototype for 'isp_s_ca' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1468:5: error: no previous prototype for 'isp_s_flt_ctrl' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1557:5: error: no previous prototype for 'get_eff_coeff' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1709:5: error: no previous prototype for 'get_afm_shift' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:1973:5: error: no previous prototype for 'isp_cproc_control' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:2047:5: error: no previous prototype for 'isp_ioc_qcap' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:2066:5: error: no previous prototype for 'isp_ioc_g_status' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:2073:5: error: no previous prototype for 'isp_ioc_g_feature' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:2106:5: error: no previous prototype for 'isp_ioc_g_feature_veresion' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_ioctl.c:2154:5: error: no previous prototype for 'isp_s_wdr_ctrl' [-Werror=missing-prototypes]

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>